apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bbb-hpa
  namespace: bbb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bbb-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k